// Use regex on document to test for a Shopify site
// Look for a DOM script element that contains `Shopify.shop =`.
// And look for `BOOMR.application = "core"`, only present on core to detect the
// back-end that rendered this page.
// Both are generated by {{content_for_header}}.
let hasDetectedShopify = false;

const scripts = document.querySelectorAll('script');
for (let i = 0; i < scripts.length; i++) {
  const content = scripts[i].textContent;
  if (typeof content === 'string') {
    if (/Shopify\.shop\s*=/.test(content)) {
      hasDetectedShopify = true;
      break
    }
  }
}

chrome.runtime.sendMessage({
  type: 'detect-shopify',
  hasDetectedShopify,
});

if (document.location.search.includes('shopify_employee')) {
  chrome.runtime.sendMessage({
    type: 'detect-shopify-employee',
    hasDetectedShopifyEmployee: true,
  });
}
